# Generated by Django 5.0.4 on 2024-05-08 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('WeekFoodsApp', '0002_alter_ingredient_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_sug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeekFoodsApp.recipe')),
                ('user_active', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeekFoodsApp.userweekfoods')),
            ],
        ),
    ]
