# Generated by Django 5.0.4 on 2024-05-07 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ingredient', models.CharField(blank='False', max_length=100, null='False', unique='True', verbose_name='Nombre')),
                ('type_food', models.CharField(blank='False', choices=[('Aceites', 'Aceites'), ('Lácteos', 'Lácteos'), ('Legumbres', 'Legumbres'), ('Setas', 'Setas'), ('Verduras', 'Verduras'), ('Frutas', 'Frutas'), ('Cereales', 'Cereales'), ('Pescado', 'Pescado'), ('Marisco', 'Marisco'), ('Carnes', 'Carnes'), ('Especias', 'Especias'), ('Frutos secos', 'Frutos secos')], max_length=30, null='False', verbose_name='Tipo de alimento')),
                ('price', models.FloatField(null='False', verbose_name='Precio')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank='False', max_length=100, null='False', verbose_name='Nombre')),
                ('elaboration', models.URLField(null='False', verbose_name='Elaboración')),
                ('when_you_eat', models.CharField(blank='False', choices=[('Comida', 'Comida'), ('Cena', 'Cena')], default='comida', max_length=7, null='False', verbose_name='Momento del día para comer')),
                ('calories', models.IntegerField(null='False', verbose_name='calorias')),
                ('ingredients', models.ManyToManyField(to='WeekFoodsApp.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='UserWeekfoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ManyToManyField(to='WeekFoodsApp.recipe')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
