# Generated by Django 5.0.4 on 2024-05-29 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeekFoodsApp', '0003_rename_recipe_userweekfoods_recipes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userweekfoods',
            old_name='recipes',
            new_name='recipe',
        ),
    ]
