# Generated by Django 5.0.4 on 2024-06-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeekFoodsApp', '0004_rename_recipes_userweekfoods_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='elaboration',
            field=models.URLField(blank='False', null='False', verbose_name='Elaboración'),
        ),
    ]
