# Generated by Django 5.0.4 on 2024-06-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeekFoodsApp', '0005_alter_recipe_elaboration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name_ingredient',
            field=models.CharField(max_length=100, unique='True', verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.FloatField(verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='type_food',
            field=models.CharField(choices=[('Aceites', 'Aceites'), ('Lácteos', 'Lácteos'), ('Legumbres', 'Legumbres'), ('Setas', 'Setas'), ('Verduras', 'Verduras'), ('Frutas', 'Frutas'), ('Cereales', 'Cereales'), ('Pescado', 'Pescado'), ('Marisco', 'Marisco'), ('Carnes', 'Carnes'), ('Especias', 'Especias'), ('Frutos secos', 'Frutos secos')], max_length=30, verbose_name='Tipo de alimento'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='calories',
            field=models.IntegerField(verbose_name='calorias'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='elaboration',
            field=models.URLField(verbose_name='Elaboración'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='when_you_eat',
            field=models.CharField(choices=[('Comida', 'Comida'), ('Cena', 'Cena')], default='comida', max_length=7, verbose_name='Momento del día para comer'),
        ),
    ]
