# Generated by Django 5.0.4 on 2024-06-04 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeekFoodsApp', '0006_alter_ingredient_name_ingredient_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='WeekFoodsApp.ingredient', verbose_name='Ingredientes'),
        ),
        migrations.AlterField(
            model_name='userweekfoods',
            name='recipe',
            field=models.ManyToManyField(to='WeekFoodsApp.recipe', verbose_name='Recetas'),
        ),
        migrations.AlterField(
            model_name='userweekfoods',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nombre de usuario'),
        ),
    ]
